# Rename this file to languages.toml to enable multilingual support
[zh-cn]
languageName = "Chinese"
languagedirection = "ltr"
title = "Dawn Kylin"
weight = 2
[en]
languageName = "English"
languagedirection = "ltr"
title = "Dawn Kylin"
weight = 1
